### ISSUE TITLE
Trouble with .run... functions.

### ISSUE THREAD

**Issue by savsen1394** [uclchem/SpectralRadex#14]
Hi, whenever I am using the .run or .run_grid() functions same error pops up:
ValueError: Expected a 1D array, got an array with shape (40, 6)

I have attached the code (radex_tutorial.txt
[radex_tutorial.txt](https://github.com/uclchem/SpectralRadex/files/15325585/radex_tutorial.txt)
) file with the error file (error.txt). I suspect there is an issue with the pandas, while it tries to read the dictionary the output values are not coming out correct.  Currently I am using pandas 1.5.3.
[error.txt](https://github.com/uclchem/SpectralRadex/files/15325569/error.txt)

Thank you

**Comment by savsen1394** [comment]
I have modified the __init_.py file which comes with radex. 
The following two lines:
32. output["QN Upper"] = qup.reshape(-1, 6).view('S6')[:nlines]
33.  output["QN Lower"] = qlow.reshape(-1, 6).view('S6')[:nlines]

have been modified to 
32. output["QN Upper"] = qup.reshape(-1, 1).view('S6')[:nlines]
33.  output["QN Lower"] = qlow.reshape(-1, 1).view('S6')[:nlines]

and the rest of the code works fine.

Thank you

**Comment by jonholdship** [comment]
It looks like you're using an older version of spectralradex, this was fixed in v1.1.5.

**Comment by savsen1394** [comment]
I was unaware of the new version since I had downloaded spectralradex quite recently and I couldn't get any later version than 1.1.4 while installing it using pip. 

I will be thankful if you could help me to get the latest version.
